import { Coffee, Flame, Moon, Sun, SunMedium, Zap } from "lucide-react";

import { AchievementDefinition } from "./types";

export const CONSISTENCY_ACHIEVEMENTS: AchievementDefinition[] = [
  // Daily Streaks Chain
  {
    id: "first_streak",
    title: "First Spark",
    description: "Build a 2-day consecutive focus streak",
    category: "consistency",
    tier: "bronze",
    xp: 50,
    icon: Flame,
    maxProgress: 2,
    badgeColor: "text-orange-400",
    borderHighlight:
      "border-orange-500/80 shadow-[0_0_12px_rgba(249,115,22,0.25)]",
    getValue: (m) => m.currentStreakDays,
  },
  {
    id: "streak_3",
    title: "Spark Ignition",
    description: "Maintain a 3-day consecutive focus streak",
    category: "consistency",
    tier: "bronze",
    xp: 100,
    icon: Flame,
    maxProgress: 3,
    badgeColor: "text-orange-400",
    borderHighlight:
      "border-orange-500/80 shadow-[0_0_12px_rgba(249,115,22,0.25)]",
    getValue: (m) => m.currentStreakDays,
  },
  {
    id: "streak_5",
    title: "Steady Momentum",
    description: "Maintain a 5-day consecutive focus streak",
    category: "consistency",
    tier: "silver",
    xp: 200,
    icon: Flame,
    maxProgress: 5,
    badgeColor: "text-orange-400",
    borderHighlight: "border-orange-400 shadow-[0_0_14px_rgba(251,146,60,0.3)]",
    getValue: (m) => m.currentStreakDays,
  },
  {
    id: "week_of_fire",
    title: "Week of Fire",
    description: "Complete a full 7-day uninterrupted focus streak",
    category: "consistency",
    tier: "silver",
    xp: 350,
    icon: Flame,
    maxProgress: 7,
    badgeColor: "text-orange-400",
    borderHighlight: "border-orange-400 shadow-[0_0_14px_rgba(251,146,60,0.3)]",
    getValue: (m) => m.currentStreakDays,
  },
  {
    id: "streak_10",
    title: "Blazing Will",
    description: "Achieve a 10-day consecutive focus streak",
    category: "consistency",
    tier: "gold",
    xp: 500,
    icon: Flame,
    maxProgress: 10,
    badgeColor: "text-orange-400",
    borderHighlight:
      "border-orange-400 shadow-[0_0_16px_rgba(251,146,60,0.35)]",
    getValue: (m) => m.currentStreakDays,
  },
  {
    id: "streak_14",
    title: "Fortnight Champion",
    description: "Unbroken consistency for 14 straight days",
    category: "consistency",
    tier: "gold",
    xp: 750,
    icon: Flame,
    maxProgress: 14,
    badgeColor: "text-orange-400",
    borderHighlight:
      "border-orange-400 shadow-[0_0_16px_rgba(251,146,60,0.35)]",
    getValue: (m) => m.currentStreakDays,
  },
  {
    id: "streak_21",
    title: "Habit Forged",
    description: "Reach 21 consecutive days of habitual deep work",
    category: "consistency",
    tier: "platinum",
    xp: 1200,
    icon: Flame,
    maxProgress: 21,
    badgeColor: "text-orange-400",
    borderHighlight:
      "border-orange-300 shadow-[0_0_18px_rgba(253,186,116,0.4)]",
    getValue: (m) => m.currentStreakDays,
  },
  {
    id: "streak_30",
    title: "Unstoppable Flow",
    description: "A legendary 30-day uninterrupted focus streak",
    category: "consistency",
    tier: "diamond",
    xp: 2000,
    icon: Flame,
    maxProgress: 30,
    badgeColor: "text-orange-400",
    borderHighlight:
      "border-orange-300 shadow-[0_0_20px_rgba(253,186,116,0.45)]",
    getValue: (m) => m.currentStreakDays,
  },

  // Daily Volume Chain
  {
    id: "double_down",
    title: "Double Down",
    description: "Complete 2 or more focus sessions in a single day",
    category: "consistency",
    tier: "bronze",
    xp: 75,
    icon: Zap,
    maxProgress: 2,
    badgeColor: "text-yellow-400",
    borderHighlight:
      "border-yellow-500/80 shadow-[0_0_12px_rgba(234,179,8,0.25)]",
    getValue: (m) => m.maxDailySessions,
  },
  {
    id: "triple_threat",
    title: "Triple Threat",
    description: "Complete 3 or more focus sessions in a single day",
    category: "consistency",
    tier: "silver",
    xp: 175,
    icon: Zap,
    maxProgress: 3,
    badgeColor: "text-yellow-400",
    borderHighlight: "border-yellow-400 shadow-[0_0_14px_rgba(250,204,21,0.3)]",
    getValue: (m) => m.maxDailySessions,
  },
  {
    id: "quad_power",
    title: "Quad Power",
    description: "Complete 4 or more focus sessions in a single day",
    category: "consistency",
    tier: "gold",
    xp: 350,
    icon: Zap,
    maxProgress: 4,
    badgeColor: "text-yellow-400",
    borderHighlight:
      "border-yellow-400 shadow-[0_0_16px_rgba(250,204,21,0.35)]",
    getValue: (m) => m.maxDailySessions,
  },

  // Time-of-Day Habits
  {
    id: "early_bird",
    title: "Early Bird",
    description: "Complete a focus session between 5:00 AM and 9:00 AM",
    category: "consistency",
    tier: "bronze",
    xp: 75,
    icon: Sun,
    maxProgress: 1,
    badgeColor: "text-amber-400",
    borderHighlight:
      "border-amber-500/80 shadow-[0_0_12px_rgba(245,158,11,0.25)]",
    getValue: (m) => (m.hasEarlyMorningSession ? 1 : 0),
  },
  {
    id: "morning_clarity",
    title: "Morning Clarity",
    description: "Complete at least 2 morning sessions (5:00 AM – 12:00 PM)",
    category: "consistency",
    tier: "silver",
    xp: 150,
    icon: SunMedium,
    maxProgress: 2,
    badgeColor: "text-amber-400",
    borderHighlight: "border-amber-400 shadow-[0_0_14px_rgba(251,191,36,0.3)]",
    getValue: (m) => m.morningSessionsCount,
  },
  {
    id: "afternoon_surge",
    title: "Afternoon Surge",
    description:
      "Power through an afternoon focus session (12:00 PM – 5:00 PM)",
    category: "consistency",
    tier: "bronze",
    xp: 75,
    icon: Coffee,
    maxProgress: 1,
    badgeColor: "text-amber-400",
    borderHighlight:
      "border-amber-500/80 shadow-[0_0_12px_rgba(245,158,11,0.25)]",
    getValue: (m) => (m.hasAfternoonSession ? 1 : 0),
  },
  {
    id: "night_owl",
    title: "Night Owl",
    description: "Complete a quiet night session between 10:00 PM and 4:00 AM",
    category: "consistency",
    tier: "bronze",
    xp: 75,
    icon: Moon,
    maxProgress: 1,
    badgeColor: "text-indigo-400",
    borderHighlight:
      "border-indigo-500/80 shadow-[0_0_12px_rgba(99,102,241,0.25)]",
    getValue: (m) => (m.hasLateNightSession ? 1 : 0),
  },
  {
    id: "weekend_warrior",
    title: "Weekend Warrior",
    description: "Focus on both Saturday and Sunday in your history",
    category: "consistency",
    tier: "silver",
    xp: 150,
    icon: Flame,
    maxProgress: 1,
    badgeColor: "text-orange-400",
    borderHighlight: "border-orange-400 shadow-[0_0_14px_rgba(251,146,60,0.3)]",
    getValue: (m) => (m.hadSatAndSun ? 1 : 0),
  },
];
