import { Bookmark, CheckCircle2, Flag, Tag } from "lucide-react";

import { AchievementDefinition } from "./types";

export const TASK_ACHIEVEMENTS: AchievementDefinition[] = [
  // Task Volume Chain
  {
    id: "first_todo",
    title: "First Checkmark",
    description: "Complete your first task from your to-do list",
    category: "tasks",
    tier: "bronze",
    xp: 50,
    icon: CheckCircle2,
    maxProgress: 1,
    badgeColor: "text-emerald-400",
    borderHighlight:
      "border-emerald-500/80 shadow-[0_0_12px_rgba(16,185,129,0.25)]",
    getValue: (m) => m.completedTodosCount,
  },
  {
    id: "task_starter_5",
    title: "Getting Things Done",
    description: "Complete 5 tasks from your to-do list",
    category: "tasks",
    tier: "bronze",
    xp: 100,
    icon: CheckCircle2,
    maxProgress: 5,
    badgeColor: "text-emerald-400",
    borderHighlight:
      "border-emerald-500/80 shadow-[0_0_12px_rgba(16,185,129,0.25)]",
    getValue: (m) => m.completedTodosCount,
  },
  {
    id: "task_crusher_10",
    title: "Task Crusher",
    description: "Complete 10 total to-do items",
    category: "tasks",
    tier: "silver",
    xp: 200,
    icon: CheckCircle2,
    maxProgress: 10,
    badgeColor: "text-emerald-400",
    borderHighlight:
      "border-emerald-400 shadow-[0_0_14px_rgba(52,211,153,0.3)]",
    getValue: (m) => m.completedTodosCount,
  },
  {
    id: "task_slayer_25",
    title: "Productivity Engine",
    description: "Complete 25 total to-do items",
    category: "tasks",
    tier: "gold",
    xp: 400,
    icon: CheckCircle2,
    maxProgress: 25,
    badgeColor: "text-emerald-400",
    borderHighlight:
      "border-emerald-400 shadow-[0_0_16px_rgba(52,211,153,0.35)]",
    getValue: (m) => m.completedTodosCount,
  },
  {
    id: "task_machine_50",
    title: "Task Titan",
    description: "Complete 50 total to-do items",
    category: "tasks",
    tier: "platinum",
    xp: 800,
    icon: CheckCircle2,
    maxProgress: 50,
    badgeColor: "text-emerald-400",
    borderHighlight:
      "border-emerald-300 shadow-[0_0_18px_rgba(110,231,183,0.4)]",
    getValue: (m) => m.completedTodosCount,
  },
  {
    id: "task_centurion_100",
    title: "Task Centurion",
    description: "Complete 100 total to-do items",
    category: "tasks",
    tier: "diamond",
    xp: 1500,
    icon: CheckCircle2,
    maxProgress: 100,
    badgeColor: "text-emerald-400",
    borderHighlight:
      "border-emerald-300 shadow-[0_0_20px_rgba(110,231,183,0.45)]",
    getValue: (m) => m.completedTodosCount,
  },

  // High Priority Chain
  {
    id: "priority_first",
    title: "High Stakes",
    description: "Complete 1 high-priority task",
    category: "tasks",
    tier: "bronze",
    xp: 75,
    icon: Flag,
    maxProgress: 1,
    badgeColor: "text-rose-400",
    borderHighlight:
      "border-rose-500/80 shadow-[0_0_12px_rgba(244,63,94,0.25)]",
    getValue: (m) => m.completedHighPriority,
  },
  {
    id: "priority_pilot_5",
    title: "Priority Pilot",
    description: "Complete 5 high-priority tasks",
    category: "tasks",
    tier: "silver",
    xp: 200,
    icon: Flag,
    maxProgress: 5,
    badgeColor: "text-rose-400",
    borderHighlight: "border-rose-400 shadow-[0_0_14px_rgba(251,113,133,0.3)]",
    getValue: (m) => m.completedHighPriority,
  },
  {
    id: "priority_master_15",
    title: "Crisis Commander",
    description: "Conquer 15 high-priority tasks",
    category: "tasks",
    tier: "gold",
    xp: 500,
    icon: Flag,
    maxProgress: 15,
    badgeColor: "text-rose-400",
    borderHighlight: "border-rose-400 shadow-[0_0_16px_rgba(251,113,133,0.35)]",
    getValue: (m) => m.completedHighPriority,
  },

  // Tag Diversity Chain
  {
    id: "tag_polymath_3",
    title: "Organized Mind",
    description: "Complete tasks across 3 different tags",
    category: "tasks",
    tier: "silver",
    xp: 150,
    icon: Tag,
    maxProgress: 3,
    badgeColor: "text-teal-400",
    borderHighlight: "border-teal-400 shadow-[0_0_14px_rgba(45,212,191,0.3)]",
    getValue: (m) => m.completedTagsCount,
  },
  {
    id: "tag_master_5",
    title: "Tag Master",
    description: "Complete tasks across 5 distinct tags",
    category: "tasks",
    tier: "gold",
    xp: 300,
    icon: Tag,
    maxProgress: 5,
    badgeColor: "text-teal-400",
    borderHighlight: "border-teal-400 shadow-[0_0_16px_rgba(45,212,191,0.35)]",
    getValue: (m) => m.completedTagsCount,
  },

  // Special Feats
  {
    id: "note_taker",
    title: "Detailed Planner",
    description: "Complete 3 tasks that have custom notes or subtext attached",
    category: "tasks",
    tier: "bronze",
    xp: 100,
    icon: Bookmark,
    maxProgress: 3,
    badgeColor: "text-fuchsia-400",
    borderHighlight:
      "border-fuchsia-500/80 shadow-[0_0_12px_rgba(217,70,239,0.25)]",
    getValue: (m) => m.completedWithNotes,
  },
];
