import { Clock, Target, Timer } from "lucide-react";

import { AchievementDefinition } from "./types";

export const FOCUS_ACHIEVEMENTS: AchievementDefinition[] = [
  // Focus Cycles Chain
  {
    id: "first_focus",
    title: "First Flow",
    description: "Complete your first pomodoro focus session",
    category: "focus",
    tier: "bronze",
    xp: 50,
    icon: Target,
    maxProgress: 1,
    badgeColor: "text-cyan-400",
    borderHighlight:
      "border-cyan-500/80 shadow-[0_0_12px_rgba(6,182,212,0.25)]",
    getValue: (m) => m.totalSessions,
  },
  {
    id: "focus_novice",
    title: "Getting in the Zone",
    description: "Complete 3 total pomodoro focus cycles",
    category: "focus",
    tier: "bronze",
    xp: 75,
    icon: Target,
    maxProgress: 3,
    badgeColor: "text-cyan-400",
    borderHighlight:
      "border-cyan-500/80 shadow-[0_0_12px_rgba(6,182,212,0.25)]",
    getValue: (m) => m.totalCycles,
  },
  {
    id: "flow_starter",
    title: "Flow Apprentice",
    description: "Complete 10 total pomodoro focus cycles",
    category: "focus",
    tier: "silver",
    xp: 150,
    icon: Target,
    maxProgress: 10,
    badgeColor: "text-cyan-400",
    borderHighlight: "border-cyan-400 shadow-[0_0_14px_rgba(34,211,238,0.3)]",
    getValue: (m) => m.totalCycles,
  },
  {
    id: "focus_adept",
    title: "Deep Worker",
    description: "Complete 25 total pomodoro focus cycles",
    category: "focus",
    tier: "gold",
    xp: 300,
    icon: Target,
    maxProgress: 25,
    badgeColor: "text-cyan-400",
    borderHighlight: "border-cyan-400 shadow-[0_0_16px_rgba(34,211,238,0.35)]",
    getValue: (m) => m.totalCycles,
  },
  {
    id: "marathon_runner",
    title: "Marathon Mind",
    description: "Complete 50 total pomodoro focus cycles",
    category: "focus",
    tier: "platinum",
    xp: 600,
    icon: Target,
    maxProgress: 50,
    badgeColor: "text-cyan-400",
    borderHighlight: "border-cyan-300 shadow-[0_0_18px_rgba(103,232,249,0.4)]",
    getValue: (m) => m.totalCycles,
  },
  {
    id: "grand_centurion",
    title: "Focus Grandmaster",
    description: "Complete 100 total pomodoro focus cycles",
    category: "focus",
    tier: "diamond",
    xp: 1200,
    icon: Target,
    maxProgress: 100,
    badgeColor: "text-cyan-400",
    borderHighlight: "border-cyan-300 shadow-[0_0_20px_rgba(103,232,249,0.45)]",
    getValue: (m) => m.totalCycles,
  },

  // Focus Minutes / Time Chain
  {
    id: "century_club",
    title: "Century Club",
    description: "Accumulate 100 total minutes of deep focus",
    category: "focus",
    tier: "bronze",
    xp: 100,
    icon: Clock,
    maxProgress: 100,
    badgeColor: "text-blue-400",
    borderHighlight:
      "border-blue-500/80 shadow-[0_0_12px_rgba(59,130,246,0.25)]",
    getValue: (m) => m.totalFocusMinutes,
  },
  {
    id: "half_day_focus",
    title: "Half-Day Immersion",
    description: "Reach 300 total minutes (5 hours) of focused work",
    category: "focus",
    tier: "silver",
    xp: 250,
    icon: Clock,
    maxProgress: 300,
    badgeColor: "text-blue-400",
    borderHighlight: "border-blue-400 shadow-[0_0_14px_rgba(96,165,250,0.3)]",
    getValue: (m) => m.totalFocusMinutes,
  },
  {
    id: "workday_master",
    title: "Workday Master",
    description: "Reach 480 total minutes (8 full hours) of productivity",
    category: "focus",
    tier: "gold",
    xp: 500,
    icon: Clock,
    maxProgress: 480,
    badgeColor: "text-blue-400",
    borderHighlight: "border-blue-400 shadow-[0_0_16px_rgba(96,165,250,0.35)]",
    getValue: (m) => m.totalFocusMinutes,
  },
  {
    id: "kilo_focus",
    title: "Kilo Focus",
    description: "Achieve 1,000 total minutes (~16.6 hours) of deep work",
    category: "focus",
    tier: "diamond",
    xp: 1000,
    icon: Clock,
    maxProgress: 1000,
    badgeColor: "text-blue-400",
    borderHighlight: "border-blue-300 shadow-[0_0_20px_rgba(147,197,253,0.45)]",
    getValue: (m) => m.totalFocusMinutes,
  },

  // Single Session Endurance Chain
  {
    id: "deep_session_45",
    title: "Deep Dive",
    description:
      "Complete a single continuous session lasting at least 45 minutes",
    category: "focus",
    tier: "silver",
    xp: 150,
    icon: Timer,
    maxProgress: 45,
    badgeColor: "text-indigo-400",
    borderHighlight:
      "border-indigo-400 shadow-[0_0_14px_rgba(129,140,248,0.3)]",
    getValue: (m) => m.longestSessionMinutes,
  },
  {
    id: "deep_session_60",
    title: "Hour of Power",
    description: "Maintain uninterrupted deep focus for 60 consecutive minutes",
    category: "focus",
    tier: "gold",
    xp: 300,
    icon: Timer,
    maxProgress: 60,
    badgeColor: "text-indigo-400",
    borderHighlight:
      "border-indigo-400 shadow-[0_0_16px_rgba(129,140,248,0.35)]",
    getValue: (m) => m.longestSessionMinutes,
  },
  {
    id: "deep_session_90",
    title: "Ultra Focus",
    description: "Conquer a massive 90-minute continuous focus session",
    category: "focus",
    tier: "platinum",
    xp: 600,
    icon: Timer,
    maxProgress: 90,
    badgeColor: "text-indigo-400",
    borderHighlight:
      "border-indigo-300 shadow-[0_0_18px_rgba(165,180,252,0.4)]",
    getValue: (m) => m.longestSessionMinutes,
  },
];
